# Use the official Python slim image.
FROM python:3.8-slim

# Set the working directory.
WORKDIR /app

# Copy the requirements file and install dependencies.
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of the application code.
COPY . .

# Expose port 8000 for the FastAPI server.
EXPOSE 8000

# Command to run the FastAPI app.
CMD ["uvicorn", "deployment.api:app", "--host", "0.0.0.0", "--port", "8000"]
